# Generated by Django 5.0.3 on 2024-03-11 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_categorymodel_options_productmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='product_title',
            field=models.CharField(help_text='Here add name of product', max_length=50),
        ),
    ]
